name = "OptimalControlProblems"
uuid = "59046045-fb9c-4c23-964f-ff0a25704f96"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "0.1.1"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"

[weakdeps]
CTDirect = "790bbbee-bee9-49ee-8912-a9de031322d5"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[extensions]
JuMPModels = "JuMP"
OptimalControlModels = "CTDirect"

[compat]
CTBase = "0.14"
CTDirect = "0.12"
JuMP = "1"
julia = "1.10"
